AManeira/Models/Pratos.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AManeira.Models
{
    public class Pratos
    {
        public Pratos()
        {
            ListaEncomendasPratos = new HashSet<EncomendasPratos>();
            ListaFotos = new HashSet<Fotos>();
        }

        /// <summary>
        /// id do prato
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// nome do prato
        /// </summary>
        public string Nome { get; set; }


        /// <summary>
        /// preço do prato
        /// </summary>
        [NotMapped]  // this anotation tells the EF that this attribute must not be represented on database
        [RegularExpression("[0-9]{1,8}[,.]?[0-9]{0,2}", ErrorMessage = "Formato não aceitável")]
        [Display(Name = "Preço")]
        public string AuxPreco { get; set; }
        public decimal Preco { get; set; }

        /// <summary>
        /// foto associada ao prato
        /// </summary>
        public string Foto { get; set; }

        /// <summary>
        /// descrição do prato
        /// </summary>
        [Display(Name = "Descrição")]
        public string Descricao { get; set; }


        /// <summary>
        /// quantidade disponível do prato
        /// </summary>
        [Display(Name = "Stock")]
        public int NumStock { get; set; }

        /// <summary>
        /// lista de encomendas do Prato
        /// </summary>
        public ICollection<EncomendasPratos> ListaEncomendasPratos { get; set; }
        /// <summary>
        /// lista de fotos do Prato
        /// </summary>
        public ICollection<Fotos> ListaFotos { get; set; }
    }
}

AManeira/Controllers/PratosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AManeira.Data;
using AManeira.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Data;
//using System.Web.Mvc;

namespace AManeira.Controllers
{
    public class PratosController : Controller
    {
        /// <summary>
        /// cria uma referência à base de dados do projeto
        /// </summary>
        private readonly ApplicationDbContext _context;

        private readonly UserManager<ApplicationUser> _userManager;

        /// <summary>
        /// esta variável contém os dados do servidor ASP .NET
        /// </summary>
        private readonly IWebHostEnvironment _webHostEnvironment;

        public PratosController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
            _userManager = userManager;
        }

        // GET: Pratos
        public async Task<IActionResult> Index()
        {
            return View(await _context.Pratos.ToListAsync());
        }

        // GET: Pratos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Pratos == null)
            {
                return RedirectToAction("Index");
            }

            var pratos = await _context.Pratos
                .Include(l => l.ListaFotos)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pratos == null)
            {
                return RedirectToAction("Index");
            }

            return View(pratos);
        }
        [Authorize(Roles = "Admin")]
        // GET: Pratos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Pratos/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Preco,AuxPreco,Foto,Descricao,NumStock")] Pratos prato)
        {
            prato.Preco = Convert.ToDecimal(prato.AuxPreco.Replace('.', ','));
            if (ModelState.IsValid)
            {
                _context.Add(prato);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(prato);
        }

        // GET: Pratos/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Pratos == null)
            {
                return RedirectToAction("Index");
            }

            var pratos = await _context.Pratos.FindAsync(id);
            if (pratos == null)
            {
                return RedirectToAction("Index");
            }
            return View(pratos);
        }

        // POST: Pratos/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Preco,AuxPreco,Foto,Descricao,NumStock")] Pratos prato)
        {
            prato.Preco = Convert.ToDecimal(prato.AuxPreco.Replace('.', ','));
            if (id != prato.Id)
            {
                return RedirectToAction("Index");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(prato);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PratosExists(prato.Id))
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(prato);
        }

        // GET: Pratos/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Pratos == null)
            {
                return RedirectToAction("Index");
            }

            var pratos = await _context.Pratos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pratos == null)
            {
                return RedirectToAction("Index");
            }

            return View(pratos);
        }

        // POST: Pratos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Pratos == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Pratos'  is null.");
            }
            var pratos = await _context.Pratos.FindAsync(id);
            if (pratos != null)
            {
                _context.Pratos.Remove(pratos);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PratosExists(int id)
        {
            return _context.Pratos.Any(e => e.Id == id);
        }

        [HttpPost]
        public async Task<JsonResult> AddToEncomenda(string idAux)
        {
            int id = Convert.ToInt32(idAux);

            //ir buscar o prato correspondente ao 'id'
            var prato = await _context.Pratos
               .Where(s => s.Id == id)
               .FirstOrDefaultAsync();

            //ir buscar o utilizador autenticado
            var user = _userManager.GetUserId(User);

            //procurar na tabela dos clientes pelo utilizador autenticado
            var cliente = await _context.Clientes
               .Where(s => s.UserID == user)
               .FirstOrDefaultAsync();

            // verificar em que encomenda por o prato
            var encomenda = await _context.Encomendas
               .Include(s=> s.ListaEncomendasPratos)
               .Where(s => s.ClienteFK == cliente.ID && s.IsActive == true)
               .FirstOrDefaultAsync();
            //criar encomenda se não existe encomenda ativa relacionada ao cliente
            if (encomenda == null)
            {
                encomenda = new Encomendas { PrecoTotal = 0, ClienteFK = cliente.ID, DataHoraEntrega=DateTime.Now, IsActive = true };
                // associar o Prato à Encomenda
                var listaPrato = new List<EncomendasPratos>();
                listaPrato.Add(new EncomendasPratos { Prato = prato, Encomenda = encomenda, Quantidade = 1 });
                encomenda.ListaEncomendasPratos = listaPrato;
                // adicionar a encomenda à BD
                _context.Encomendas.Add(encomenda);
                await _context.SaveChangesAsync();
                //devolver caso de sucesso em Json
                return Json(new { id = "1" });
            }

            /* se chego aqui, a Encomenda já existia...
             */

            //ver se o prato já foi adicionado à encomenda
            var registo = await _context.EncomendasPratos
               .Where(s => s.PratoFK == id && s.EncomendaFK == encomenda.Id)
               .FirstOrDefaultAsync();

            if (registo == null)
            {
                // se não foi, adicionar à encomenda
                var pratoAdd = new EncomendasPratos { Prato = prato, Encomenda = encomenda, Quantidade = 1 };
                encomenda.ListaEncomendasPratos.Add( pratoAdd);

                // atualizar os dados na BD
                _context.Entry(encomenda).State = EntityState.Modified;
                await _context.SaveChangesAsync();
                //devolver caso de sucesso em Json
                return Json(new { id = "1" });
            }
            //se já foi, ir buscar a quantidade e incrementar
            var qnt = registo.Quantidade + 1;

            //adicionar novamente com a quantidade incrementada
            var pratoAdd2 = new EncomendasPratos { Prato = prato, Encomenda = encomenda, Quantidade = qnt };
            encomenda.ListaEncomendasPratos.Add(pratoAdd2);

            //remover o registo antigo
            _context.Remove(registo);

            // atualizar os dados na BD
            _context.Entry(encomenda).State = EntityState.Modified;
            await _context.SaveChangesAsync();
            //devolver caso de sucesso em Json
            return Json(new { id = "1" });
        }
    }

}

AManeira/Views/Pratos/Create.cshtml
@model AManeira.Models.Pratos

@{
    ViewData["Title"] = "Novo prato";
}

<h1>Adicionar</h1>

<h4>Prato</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuxPreco" class="control-label"></label>
                <input asp-for="AuxPreco" class="form-control" />
                <span asp-validation-for="AuxPreco" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Foto" class="control-label"></label>
                <input type="file" name="Foto" class="form-control" accept=".jpg,.png"  />
                <span asp-validation-for="Foto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumStock" class="control-label"></label>
                <input asp-for="NumStock" class="form-control" />
                <span asp-validation-for="NumStock" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Adicionar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar à ementa</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AManeira/Views/Pratos/Delete.cshtml
@model AManeira.Models.Pratos

@{
    ViewData["Title"] = "Apagar";
}

<h1>Apagar</h1>

<h3>Tens a certeza que queres eliminar este prato?</h3>
<div>
    <h4>Pratos</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AuxPreco)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Preco)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Foto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Foto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumStock)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumStock)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar à ementa</a>
    </form>
</div>

AManeira/Views/Pratos/Details.cshtml
@model AManeira.Models.Pratos

@{
    ViewData["Title"] = "Detalhes";
}

<h1>@Html.DisplayFor(model => model.Nome)</h1>

<div>
    <h4>Detalhes</h4>
    <hr />
    <!--<dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Preco)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Preco)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Foto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Foto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumStock)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumStock)
        </dd>
    </dl>-->
       
</div>

    @foreach (var item in Model.ListaFotos ) {
        <img src="~/imagens/@item.Name"
        title="@Html.DisplayFor(model => model.Nome)" height="150"/>

}
<div style="text-align:center">
    <!--
        //slider das fotos associadas ao prato
    -->
    <br />
   <img src="~/imagens/@Html.DisplayFor(model => model.Foto)"
        alt="Fotografia do prato @Html.DisplayFor(model => model.Nome)"
        title="@Html.DisplayFor(model => model.Nome)" height="300"/>
    <div>
        @Html.DisplayFor(model => model.Descricao)
    </div>
    <br />
    @if (User.IsInRole("Cliente"))
    {
            <input type="button" class="botao" id="addDish" onclick="AjaxFormSubmit(@Model?.Id)" value="Adicionar à encomenda (+@Html.DisplayFor(model => model.Preco)€)"/>
    }
    <br />
    Stock do produto: @Html.DisplayFor(model => model.NumStock)
</div>
<div>
    @if(User.IsInRole("Admin")){
        <div>
        <a asp-action="Edit" asp-route-id="@Model?.Id">Editar prato</a> |
        <a asp-action="Delete" asp-route-id="@Model?.Id">Eliminar prato</a> |
        </div>
    }
    <a asp-action="Index">Ver Pratos</a>
</div>


<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript" src="https://ajax.cdnjs.com/ajax/libs/json2/20110223/json2.js"></script>
    <script type="text/javascript">
        function AjaxFormSubmit(i) {
        var pratoID = i;
        $.ajax({
            async: true,
            type: "POST",
            url: "/Pratos/AddToEncomenda",
            data: { idAux: pratoID},
            //contentType: 'application/json',
            //dataType: "json",
            success: function (response) {
                if (response == 1) {
                    // incrementa o nº de itens no carrinho de compras
                    // ...
                    // mostra msg de sucesso
                    alert("Prato adicionado!");
                }
                if (response == 0) {
                    alert("Erro ao adicionar prato :/");
                }
            }
        });
    }
</script>

AManeira/Views/Pratos/Edit.cshtml
@model AManeira.Models.Pratos

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar</h1>

<h4>Prato</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuxPreco" class="control-label"></label>
                <input asp-for="AuxPreco" class="form-control" />
                <span asp-validation-for="AuxPreco" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Foto" class="control-label"></label>
                <input asp-for="Foto" class="form-control" />
                <span asp-validation-for="Foto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumStock" class="control-label"></label>
                <input asp-for="NumStock" class="form-control" />
                <span asp-validation-for="NumStock" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar à ementa</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AManeira/Views/Pratos/Index.cshtml
@model IEnumerable<AManeira.Models.Pratos>

@{
    ViewData["Title"] = "Ementa";
}

<h1>Ementa da semana</h1>
@if (User.IsInRole("Admin"))
{
    <p>
        <a asp-action="Create">Adicionar prato</a>
    </p>
}
@foreach (var item in Model)
{
    <div class="pratos">
        <a asp-action="Details" asp-controller="Pratos" asp-route-id="@item.Id" target="_self">
            <img src="~/imagens/@item.Foto"
             alt="Fotografia do prato @Html.DisplayFor(modelItem => item.Nome)"
             title="@item.Nome"
             height="150" />
        </a>
        <div>@Html.DisplayFor(modelItem => item.Nome)</div>
        @if (!User.IsInRole("Cliente"))
        {
            <div>@Html.DisplayFor(modelItem => item.Preco)€</div>
        }
        @if (User.IsInRole("Cliente"))
        {
            <input type="button" class="botao" id="addDish" onclick="AjaxFormSubmit(@item.Id)" value="Adicionar à encomenda (+@Html.DisplayFor(modelItem => item.Preco)€)" />
        }
    </div>

}

@if(!User.Identity.IsAuthenticated){
    <p>Por favor inicie sessão ou crie uma conta para poder fazer uma encomenda.</p>
}


<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script type="text/javascript" src="https://ajax.cdnjs.com/ajax/libs/json2/20110223/json2.js"></script>
<script type="text/javascript">
    function AjaxFormSubmit(i) {
        var pratoID = i;
        $.ajax({
            async: true,
            type: "POST",
            url: "/Pratos/AddToEncomenda",
            data: { idAux: pratoID},
            //contentType: 'application/json',
            //dataType: "json",
            success: function (response) {
                if (response = 1) {
                    // incrementa o nº de itens no carrinho de compras
                    // ...
                    // mostra msg de sucesso
                    alert("Prato adicionado!");
                }
                if (response = 0) {
                    alert("Erro ao adicionar prato :/");
                }
            }
        });
    }
</script>